FPS = 30

DEFAULT_ASSET_SIZE = 64
DEFAULT_MAP_SIZE = 12

WINDOW_HEIGHT = DEFAULT_ASSET_SIZE * DEFAULT_MAP_SIZE
WINDOW_WIDTH = DEFAULT_ASSET_SIZE * DEFAULT_MAP_SIZE
PADDING = 64

TRASHES_COUNT = 4

WHITE_COLOR = (255, 255, 255)

TRASH_BOTTLE = "TRASH_BOTTLE"
TRASH_CAN = "TRASH_CAN"

FREE_SPACE = 0
OBSTACLE = 1

R_RIGHT = "R_RIGHT"
R_LEFT = "R_LEFT"
R_UP = "R_UP"
R_DOWN = "R_DOWN"

